display_name: VPN4ยง
url: https://github.com/a4e/vpn4tv_hiddify
license: Other

packager: vpn4tv
packagerEmail: linux@vpn4tv.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/source/ic_launcher_border.png

keywords:
  - Hiddify
  - Proxy
  - VPN
  - V2ray
  - Nekoray
  - Xray
  - Psiphon
  - OpenVPN

generic_name: Hiddify

group: Applications/Internet

startup_notify: true
